name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements-dev.txt
      - run: pytest
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'us-east-1'
          role-to-assume: 'arn:aws:iam::330866750121:role/GHAuth'
      - run: aws sts get-caller-identity
      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr-login
      - run: | 
            IMAGE=${{ steps.ecr-login.outputs.registry }}/genshin-app:${{ github.sha }}
            docker build -t $IMAGE .
            docker push $IMAGE
      - run: aws ecs describe-task-definition --task-definition genshin-task --query taskDefinition > task-definition.json
      - uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: './task-definition.json'
          container-name: 'genshin-app'
          image: ${{ steps.ecr-login.outputs.registry }}/genshin-app:${{ github.sha }}
        id: render
      - uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render.outputs.task-definition }}
          service: genshin-service
          cluster: genshin-cluster
          wait-for-service-stability: true
    if: github.ref == 'refs/heads/master'
    needs: test